# Generated by Django 5.2.3 on 2025-07-23 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='is_solved',
            field=models.BooleanField(default=False),
        ),
    ]
