# Generated by Django 5.2.3 on 2025-07-29 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterstudent', '0002_alter_masterstudent_photo_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterstudent',
            name='password',
            field=models.CharField(blank=True, default='admin', max_length=100, null=True),
        ),
    ]
