# Generated by Django 5.2.3 on 2025-07-29 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterstudent', '0003_masterstudent_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterstudent',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
