# Generated by Django 5.2.3 on 2025-07-11 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_Visitors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('visiting_whom', models.CharField(max_length=50)),
                ('purpose', models.TextField()),
                ('in_time', models.DateField()),
                ('out_time', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
