# Generated by Django 5.2.3 on 2025-07-12 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_Studentmarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('student_class', models.CharField(max_length=50)),
                ('sub1', models.IntegerField()),
                ('sub2', models.IntegerField()),
                ('sub3', models.IntegerField()),
                ('sub4', models.IntegerField()),
                ('sub5', models.IntegerField()),
                ('sub6', models.IntegerField()),
                ('sub7', models.IntegerField()),
                ('total', models.IntegerField()),
                ('percentage', models.IntegerField()),
            ],
        ),
    ]
