# Generated by Django 5.2.3 on 2025-07-19 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_studentmarks',
            name='gr_no',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
