# Generated by Django 5.2.3 on 2025-07-14 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HostelFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('student_class', models.CharField(max_length=50)),
                ('fee_amount', models.IntegerField()),
                ('fee_paid', models.IntegerField()),
                ('due_date', models.DateField()),
                ('paid_on', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
