# Generated by Django 5.2.3 on 2025-07-18 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees_management', '0002_feepayment_delete_hostelfee'),
    ]

    operations = [
        migrations.AddField(
            model_name='feepayment',
            name='mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='village',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
